### ISSUE TITLE
--scale does nothing, it is not implemented

### ISSUE THREAD

**Issue by egedib** [ychfan/wdsr#2]
As your example says:
`python trainer.py --dataset div2k --eval_datasets div2k set5 bsds100 urban100 --model wdsr --scale 2 --job_dir ./wdsr_x2 --eval_only`

Interestingly, the trainer.py code does not contain the scale parameter. So how can I super resolve an image to 2-3-4x size and get metrics from the super-resolved image?

**Comment by ychfan** [comment]
Just specify `--scale`
